apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306  # MySQL default port
      targetPort: 3306
