apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::544378344870:role/LabRole  # If using IRSA
  #namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>



