apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mydb
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-deployment-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: password
          ports:
            - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always

