apiVersion: v1
kind: Namespace
metadata:
  name: final
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: final
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: final
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s 
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: final
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.28.1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        command:
        - "/bin/prometheus"
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.console.libraries=/etc/prometheus/console_libraries"
        - "--web.console.templates=/etc/prometheus/consoles"
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-server-conf
