apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: final  # Specify the namespace where the role applies
  name: CLO835
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list"]
