apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: myapp-deployment-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
          env:
          - name: DBHOST
            value: "mysql-service.mydb.svc.cluster.local"
          - name: DBPORT
            value: "3306"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: password
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: user
          - name: APP_COLOR
            value: "blue"
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
