apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: myapp
  labels:
    my_maniType: pod
    version: v1
spec:
  serviceAccountName: s3-access-sa
  containers:
    - name: myappcontainer
      image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
      env:
        - name: DBHOST
          value: "10.244.0.17"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: user
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password
        - name: APP_COLOR
          value: "blue"
      ports:
        - containerPort: 81
  dnsPolicy: ClusterFirst
  restartPolicy: Always

