apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clo835
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"] # "read" operations are represented by "get" and "list", added "create" as per requirement
