apiVersion: v1
kind: ConfigMap
metadata:
  name: group11
  namespace: final
data:
  BACKGROUND_IMAGE: "https://finalproject-group11.s3.amazonaws.com/back2.jpeg"
  GROUP_NAME: "GROUP11"
  DBHOST: "mysql.sqldb.svc.cluster.local"
  DBPORT: "3306"
  DBUSER: "root"
  DBPW: "pw"
  DATABASE: "employees"
  APP_NAME: "my_app"
  APP_COLOR: "blue"
  S3_BUCKET_URL: "https://finalproject-group11.s3.amazonaws.com/back2.jpeg"
