apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0ea9f8e7db44c5d98
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  #namespace: final
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:db_fp01
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: app-config
        # env:
        # - name: DBUSER
        #   valueFrom:
        #     secretKeyRef:
        #       name: mydb-secret
        #       key: user
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: password
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc

