apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/your-iam-role  # If using IRSA
  #namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
