apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app_fp01
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: user
        - name: DBPW
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3
