apiVersion: v1
kind: Service
metadata:
  name: flask-mysql-service
spec:
  selector:
    app: webapp  # Match the labels of the Flask application pods
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080  # Adjust the port as needed
      targetPort: 81  # Point to the port on which the Flask application is listening
      nodePort: 30000
