apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  S3_BUCKET: "finalproject-group11"
  BACKGROUND_IMAGE_KEY: "carved_faces.jpg"
  GROUP_NAME: "GROUP11"
  DBHOST: "172.17.0.2"
  DBPORT: "3306"
  export DBUSER: "root"
  export DBPW: "pw"
  DATABASE: "employees"
  S3_BUCKET_URL: "https://finalproject-group11.s3.amazonaws.com/carved_faces.jpg"