apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  namespace: myapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: myapp-rs-container
          image: 544378344870.dkr.ecr.us-east-1.amazonaws.com/clo835-week4:app
          env:
            - name: DBHOST
              value: "mysql-service.mydb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: user
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mydb-secret
                  key: password
            - name: APP_COLOR
              value: "blue"
          ports:
            - containerPort: 80
